### PR TITLE
Proper Success Response Handling

### LINKED ISSUE #110: Update-MgUserEvent throws expeption but is running fine
When running  `Update-MgUserEvent -UserId X -EventId X -Subject  X`  i get the folling error but subject gets changed as expected.

```
Update-MgUserEvent : The server responded with an unrecognized response, Status: OK
At line:11 char:10
+          Update-MgUserEvent -UserId $Mail -EventId $_.Id -Subject $_. ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = surf...oftGraphEvent }:<>f__AnonymousType513) [Update-MgUserEvent_UpdateExpanded], RestException1
    + FullyQualifiedErrorId : OK,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUserEvent_UpdateExpanded
```

### LINKED ISSUE #271: Allow customers to iterate collection of pages based on their PageSize/top.
When `-PageSize` and `-All` are used together, we should fetch all items in the page size specified by the customer. The current paging design defaults to fetching the total number of items in `-PageSize`, and does not iterate through the collection of pages.

This is a follow-up to #266

### PR DESCRIPTION
**Pull request by peombwa**
This PR closes #110 and #198 by adding  `OverrideOnDefault` method on `PSCmdlet`. It will ensure cmdlets won't fail when a service returns a success code that's not defined in the OpenAPI coc. The  `OverrideOnDefault` will be added to the generated cmdlet at generation time by the directive in [readme.graph.md](https://github.com/microsoftgraph/msgraph-sdk-powershell/compare/po/successResponse?expand=1#diff-f6090dc5a1d5d42d140553e4691c12adR391).

The generated code will call `OverrideOnDefault` after considering the status code defined in the OpenAPI doc before giving a response a blanket success if its status code is 2xx as shown below.
image
image

The PR also closes #271 by allowing customers to specify a custom `-PageSize` when iterating through collection of pages as described in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/275.
image

#### Checklist Before Merge
- [ ] Merge #254 and #255 .
- [ ] Retest the directive with the new project structure with profiles.

[AB#5066](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5066)
[AB#5067](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5067)

### CODE REVIEW

**Comment by KirkMunro** [comment]
One thing to consider with this as a fix for #271:

Making `-PageSize` properly control the page size while allowing users to retrieve all records is the right thing to do.

But `-PageSize` currently has `-Limit` and `-Top` as aliases, and neither of those aliases are appropriate for `-PageSize` because they are about limiting the overall number of records returned, not about controlling the size of the pages used to retrieve those records.

I think `-Limit` should be broken out into its own parameter with `-Top` as an alias to work like `-PageSize` did before this change.

Related: #275

File: tools/Custom/ListCmdlet.cs [hunk 1]
```diff
@@ -84,11 +101,8 @@ public bool ShouldIteratePages(global::System.Collections.Generic.Dictionary<str
         {
             iteratedPages++;
             totalFetchedItems += itemsCount;
-            if ((boundParameters.ContainsKey("All") && !boundParameters.ContainsKey("PageSize")) ||
-                (boundParameters.ContainsKey("PageSize") && totalFetchedItems < originalPageSize))
-                return true;
-            else
-                return false;
+
+            return limit == default || totalFetchedItems < limit;
```
Comment (ddyett) [inline tools/Custom/ListCmdlet.cs:105]: may be helpful to add some quick comments.  For example 'we iterate if there's no top/limit parameter or if there are more items to fetch'

File: tools/Custom/ListCmdlet.cs [hunk 2]
```diff
@@ -56,26 +52,47 @@ public partial class ListCmdlet : global::System.Management.Automation.PSCmdlet
...
+            }
+
+            // Move `-Top` parameter to `limit` parameter.
+            if (invocationInfo.BoundParameters.ContainsKey("Top"))
+            {
+                limit = top;
+            }
+
+            // Explicitly set `-PageSize` as our $top parameter.
+            invocationInfo.BoundParameters["Top"] = invocationInfo.BoundParameters.ContainsKey("PageSize") ? PageSize : DefaultPageSize;
```
Comment (ddyett) [inline tools/Custom/ListCmdlet.cs:84]: why do we need to do this?

File: tools/Custom/ListCmdlet.cs [hunk 3]
```diff
@@ -56,26 +52,47 @@ public partial class ListCmdlet : global::System.Management.Automation.PSCmdlet
...
+            top = (int)invocationInfo.BoundParameters["Top"];
+
+            if (limit != default)
+            {
+                requiredPages = limit / top;
```
Comment (ddyett) [inline tools/Custom/ListCmdlet.cs:89]: this line just looks weird as you'd expect limit/pageSize

Comment (peombwa) [reply tools/Custom/ListCmdlet.cs:89]: That's the intent, let me clean this up.

File: tools/Custom/ListCmdlet.cs (hunk 2 above)
Comment (peombwa) [reply tools/Custom/ListCmdlet.cs:84]: We need it in order to construct a URL with a `$top` query parameter in the generated cmdlets. `PageSize` is a just a runtime parameter and is never serialized. Top/Limit on the other hand is a query parameter that's defined in the OpenAPI doc, and it will be serialized as `$top` query parameter.
``` cs
await this.Client.UsersUserListUser(this.InvocationInformation.BoundParameters.ContainsKey("Top") ? Top : default(int?), this.InvocationInformation.BoundParameters.ContainsKey("Skip") ? Skip : default(int?)...
 ```

**Comment by peombwa** [comment]
Due to COGs concerns, we will not fetch all records from the service by default unless the user explicitly opts-in via `-All` parameter. See discussion [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/275#issuecomment-653796289).

**Comment by peombwa** [comment]
@ddyett, @darrelmiller, I've updated the PR to address the COGs concerns with fetching all pages by default. With the update made in https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/272/commits/d4f87979970891891870e4dcd3bb6c8fe155a9d5, we will fetch a single page of 100 items by default. `-All` parameter can then be used to fetch all items, and `-PageSize` to specify your desired page size. The new behavior will be as follows:
 
image
cc @KirkMunro
