### PR TITLE
Fixes request content cloning exception in .NET 4.x

### LINKED ISSUE #2191: Update-MgUser - Cannot access a disposed object System.Net.Http.StringContent
When I run `Update-MgUser -Id "id-of-user" -DisplayName "the name"` I get the following error:
`Update-MgUser : One or more errors occurred`

Interestingly, the name change is applied, the error is while reading the response.
`Get-MgUser` works as expected.

`$error[0].Exception.ToString()` shows
```
System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.StringContent'.
   at System.Net.Http.HttpContent.CheckDisposed()
   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context)
   at Microsoft.Graph.PowerShell.HttpMessageLogFormatter.<CloneAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.HttpMessageLogFormatter.<GetHttpRequestLogAsync>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Graph.PowerShell.EventFactory.CreateLogEvent(Task`1 message)
   at Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUser_UpdateExpanded.<>c__DisplayClass424_0.<Microsoft.Graph.PowerShell.Runtime.IEventListener.Signal>b__1()
   at Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUser_UpdateExpanded.<Microsoft-Graph-PowerShell-Runtime-IEventListener-Signal>d__424.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Module.<OnResponseCreated>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Module.<EventHandler>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Module.<Signal>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUser_UpdateExpanded.<Microsoft-Graph-PowerShell-Runtime-IEventListener-Signal>d__424.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Users.<UserUpdateUser_Call>d__697.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Graph.PowerShell.Users.<UserUpdateUser_Call>d__697.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Users.<UserUpdateUser>d__695.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUser_UpdateExpanded.<ProcessRecordAsync>d__426.MoveNext()
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.StringContent'.
   at System.Net.Http.HttpContent.CheckDisposed()
   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context)
   at Microsoft.Graph.PowerShell.HttpMessageLogFormatter.<CloneAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.HttpMessageLogFormatter.<GetHttpRequestLogAsync>d__1.MoveNext()<---
```

This was working a few weeks ago, not sure why this is occurring now.

Powershell v5.1.22621.1778
Tested in pwsh and the error does not occur.

Microsoft.Graph v2.1.0

### PR DESCRIPTION
**Pull request by peombwa**
﻿

Fixes #2191

### Changes proposed in this pull request

- Changes log formatter's request cloning logic to try cloning the request content and skip if the content has already been disposed by the HttpClient. This behavior is only unique to VS Code extension running PowerShell 5.1 (.NET 4.x) and was [fixed in .NET core+](https://github.com/dotnet/corefx/pull/19082).

### CODE REVIEW

File: tools/Custom/HttpMessageLogFormatter.cs [hunk 1]
```diff
@@ -34,27 +34,34 @@ internal static async Task<HttpRequestMessage> CloneAsync(this HttpRequestMessag
...
+                            retryCount = maxRetryCount;
+                        }
+                        catch (InvalidOperationException)
+                        {
+                            retryCount++;
+                        }
                     }
                 }
+                catch
+                {
```
Comment (MIchaelMainer) [inline tools/Custom/HttpMessageLogFormatter.cs:63]: If there was a content body, but the request was disposed before we can finish reading, I think it may be good to communicate that this occurred in the logs at `stringBuilder.AppendLine($"Body:{Environment.NewLine}{SanitizeBody(body)}{Environment.NewLine}");`

Comment (peombwa) [reply tools/Custom/HttpMessageLogFormatter.cs:63]: Good point! I'll update the PR with the suggestion.

**Review by MIchaelMainer — APPROVED** [review]

**Comment by bunderwood** [comment]
@peombwa thank you so much! This completely resolved my issue within VS Code. Such a relief.
