### PR TITLE
IGR Error Fixes

### LINKED ISSUE #296: Invoke-GraphRequest fails for the following scenarios.
1. When a GET call with a query parameter is made to `Invoke-GraphRequest`, it throws a null exception at [InvokeGraphRequest.cs#L352](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/Authentication/Authentication/Cmdlets/InvokeGraphRequest.cs#L352) because we are calling `.FormatDictionary()` on a null `bodyAsDictionary`. We should check if `Body` is null before attempting to convert it to an `IDictionary`.
**Repro** - `Invoke-GraphRequest -Uri 'https://graph.microsoft.com/beta/groups?$count=true'`.

2. When a PowerShell hashtable with values is passed to `-Headers` parameter, a type conversion exception is thrown. This is because the parameter is written to accept `IDictionary<string,string>`, and not `IDictionary`. A non-generic dictionary maps to a PowerShell hashtable.
**Repro** - `Invoke-GraphRequest -Uri 'https://graph.microsoft.com/beta/groups?$count=true' -Headers @{"ConsistencyLevel" = "eventual"}`

### PR DESCRIPTION
**Pull request by finsharp**
Ensure that Connect-Graph has been prior called before IGR is called.
Change Headers to non-generic Dictionary.
Traverse nested json.
Add resource messages for error messages.
Provide ability to pass relative URL as well as query params.

fixes #296

### CODE REVIEW

File: src/Authentication/Authentication/Cmdlets/InvokeGraphRequest.cs [hunk 1]
```diff
@@ -25,13 +25,15 @@ public class InvokeGraphRequest : PSCmdlet
...
         private readonly InvokeGraphRequestUserAgent _graphRequestUserAgent;
+        private readonly GraphSession _graphSession;
         private string _originalFilePath;
 
         public InvokeGraphRequest()
         {
             _cancellationTokenSource = new CancellationTokenSource();
             _graphRequestUserAgent = new InvokeGraphRequestUserAgent(this);
             Authentication = GraphRequestAuthenticationType.Default;
+            _graphSession = GraphSession.Instance;
```
Comment (peombwa) [inline src/Authentication/Authentication/Cmdlets/InvokeGraphRequest.cs:36]: `GraphSession.Instance` is a static readonly property. There is no need to store it a variable, it also has the benefit of being thread safe.

Comment (finsharp) [reply src/Authentication/Authentication/Cmdlets/InvokeGraphRequest.cs:36]: What conditions make AuthContext null?

File: src/Authentication/Authentication/Properties/Resources.resx [hunk 2]
```diff
@@ -196,4 +196,13 @@
   <data name="InferFileNameOutFilePathConflict" xml:space="preserve">
     <value>The cmdlet cannot run because the following conflicting parameters are specified: {0} and {1}. Specify either {0} or {1} then retry.</value>
   </data>
+  <data name="NotConnectedToGraphException" xml:space="preserve">
+    <value>The cmdlet cannot run because Authentication is set to {0} and Connect-Graph was not called. Invoke 'Connect-Graph' or specify Authentication to be 'UserProvidedToken' and Provide a Token then retry</value>
```
Comment (peombwa) [inline src/Authentication/Authentication/Properties/Resources.resx:200]: :nit
```suggestion
    <value>The cmdlet cannot run because Authentication is set to {0} and Connect-Graph was not called. Invoke 'Connect-Graph' or specify an authentication token to 'UserProvidedToken' then retry.</value>
```

Comment (finsharp) [reply src/Authentication/Authentication/Properties/Resources.resx:200]: The original version is attempting to inform the user to do the following. 
`Invoke-GraphRequest -Token $token -Authentication UserProvidedToken`
